In [1]:
import pandas as pd
df = pd.read_csv("./finalData/Apache-0001-classification.csv")

In [5]:
(df["TP"].mean()+df["TN"].mean())/(df["TP"].mean()+df["TN"].mean()+df["FP"].mean()+df["FN"].mean())

0.8918964076858813

In [6]:
import os
os.listdir("./finalData/")

['HIPAcc-0002-regression.csv',
 'HSMGP-0001-classification.csv',
 'HIPAcc-0001-classification.csv',
 'BerkeleyJ-0001-classification.csv',
 'SQLite-0001-classification.csv',
 'Dune-0002-regression.csv',
 'JavaGC-0001-classification.csv',
 'LLVM-0002-regression.csv',
 'LLVM-0001-classification.csv',
 'BerkeleyC-0002-regression.csv',
 'Apache-0002-regression.csv',
 'SQLite-0002-regression.csv',
 'HSMGP-0002-regression.csv',
 'Dune-0001-classification.csv',
 '.ipynb_checkpoints',
 'BerkeleyC-0001-classification.csv',
 'Apache-0001-classification.csv',
 'BerkeleyJ-0002-regression.csv']

In [21]:
results = []
for i in os.listdir("./finalData/"):
    if i==".ipynb_checkpoints":
        continue
    df = pd.read_csv("./finalData/"+i)
    result = {}
    result["name"] = i.split("-")[0]
    result["type"] = i.split("-")[2].split(".")[0]
    result["Accuracy"] = (df["TP"].mean()+df["TN"].mean())/(df["TP"].mean()+df["TN"].mean()+df["FP"].mean()+df["FN"].mean())
    result["Precision"] = (df["TP"].mean())/(df["TP"].mean()+df["FP"].mean())
    result["Recall"] = (df["TP"].mean())/(df["TP"].mean()+df["FN"].mean())
    result["Specificity"] = (df["TN"].mean())/(df["TN"].mean()+df["FP"].mean())
    result["NPV"] = (df["TN"].mean())/(df["TN"].mean()+df["FN"].mean())
    results.append(result)
    
dfResults = pd.DataFrame(results)
dfResults

,Accuracy,NPV,Precision,Recall,Specificity,name,type
0,0.970209,0.969473,0.970948,0.969419,0.970999,HIPAcc,regression
1,0.948702,0.947491,0.949921,0.947319,0.950085,HSMGP,classification
2,0.967466,0.967207,0.967726,0.967182,0.967750,HIPAcc,classification
3,0.923854,0.924671,0.923025,0.923517,0.924186,BerkeleyJ,classification
4,0.739396,0.733742,0.745336,0.727083,0.751702,SQLite,classification
5,0.924593,0.925955,0.923238,0.926123,0.923063,Dune,regression
6,0.971959,0.971937,0.971980,0.971866,0.972050,JavaGC,classification
7,0.922256,0.924185,0.920339,0.924332,0.920185,LLVM,regression
8,0.915588,0.916719,0.914459,0.916725,0.914453,LLVM,classification
9,0.987046,0.987204,0.986889,0.987193,0.986899,BerkeleyC,regression
10,0.906843,0.910886,0.902552,0.905156,0.908423,Apache,regression
11,0.745185,0.739554,0.751093,0.733222,0.757141,SQLite,regression
12,0.958411,0.958257,0.958565,0.958220,0.958603,HSMGP,regression
13,0.926185,0.926026,0.926344,0.925931,0.926439,Dune,classification
14,0.985175,0.985051,0.985299,0.985030,0.985320,BerkeleyC,classification
15,0.891896,0.894774,0.888817,0.887552,0.895967,Apache,classification
16,0.932421,0.934906,0.929919,0.934180,0.930688,BerkeleyJ,regression

In [23]:
dfResults[dfResults["type"]=="classification"].sort_values("name")

,Accuracy,NPV,Precision,Recall,Specificity,name,type
15,0.891896,0.894774,0.888817,0.887552,0.895967,Apache,classification
14,0.985175,0.985051,0.985299,0.985030,0.985320,BerkeleyC,classification
3,0.923854,0.924671,0.923025,0.923517,0.924186,BerkeleyJ,classification
13,0.926185,0.926026,0.926344,0.925931,0.926439,Dune,classification
2,0.967466,0.967207,0.967726,0.967182,0.967750,HIPAcc,classification
1,0.948702,0.947491,0.949921,0.947319,0.950085,HSMGP,classification
6,0.971959,0.971937,0.971980,0.971866,0.972050,JavaGC,classification
8,0.915588,0.916719,0.914459,0.916725,0.914453,LLVM,classification
4,0.739396,0.733742,0.745336,0.727083,0.751702,SQLite,classification

In [24]:
dfResults[dfResults["type"]=="classification"][["name","Accuracy","Precision","Recall","Specificity","NPV"]].sort_values("name")

         name  Accuracy  Precision    Recall  Specificity       NPV
15     Apache  0.891896   0.888817  0.887552     0.895967  0.894774
14  BerkeleyC  0.985175   0.985299  0.985030     0.985320  0.985051
3   BerkeleyJ  0.923854   0.923025  0.923517     0.924186  0.924671
13       Dune  0.926185   0.926344  0.925931     0.926439  0.926026
2      HIPAcc  0.967466   0.967726  0.967182     0.967750  0.967207
1       HSMGP  0.948702   0.949921  0.947319     0.950085  0.947491
6      JavaGC  0.971959   0.971980  0.971866     0.972050  0.971937
8        LLVM  0.915588   0.914459  0.916725     0.914453  0.916719
4      SQLite  0.739396   0.745336  0.727083     0.751702  0.733742

In [25]:
dfResults[dfResults["type"]=="regression"][["name","Accuracy","Precision","Recall","Specificity","NPV"]].sort_values("name")

         name  Accuracy  Precision    Recall  Specificity       NPV
10     Apache  0.906843   0.902552  0.905156     0.908423  0.910886
9   BerkeleyC  0.987046   0.986889  0.987193     0.986899  0.987204
16  BerkeleyJ  0.932421   0.929919  0.934180     0.930688  0.934906
5        Dune  0.924593   0.923238  0.926123     0.923063  0.925955
0      HIPAcc  0.970209   0.970948  0.969419     0.970999  0.969473
12      HSMGP  0.958411   0.958565  0.958220     0.958603  0.958257
7        LLVM  0.922256   0.920339  0.924332     0.920185  0.924185
11     SQLite  0.745185   0.751093  0.733222     0.757141  0.739554

In [41]:
dfResults[(dfResults["name"]!="JavaGC")][["name","type","Accuracy","Precision","Recall","Specificity","NPV"]].sort_values(["name","type"])

,name,type,Accuracy,Precision,Recall,Specificity,NPV
15,Apache,classification,0.891896,0.888817,0.887552,0.895967,0.894774
10,Apache,regression,0.906843,0.902552,0.905156,0.908423,0.910886
14,BerkeleyC,classification,0.985175,0.985299,0.985030,0.985320,0.985051
9,BerkeleyC,regression,0.987046,0.986889,0.987193,0.986899,0.987204
3,BerkeleyJ,classification,0.923854,0.923025,0.923517,0.924186,0.924671
16,BerkeleyJ,regression,0.932421,0.929919,0.934180,0.930688,0.934906
13,Dune,classification,0.926185,0.926344,0.925931,0.926439,0.926026
5,Dune,regression,0.924593,0.923238,0.926123,0.923063,0.925955
2,HIPAcc,classification,0.967466,0.967726,0.967182,0.967750,0.967207
0,HIPAcc,regression,0.970209,0.970948,0.969419,0.970999,0.969473
1,HSMGP,classification,0.948702,0.949921,0.947319,0.950085,0.947491
12,HSMGP,regression,0.958411,0.958565,0.958220,0.958603,0.958257
8,LLVM,classification,0.915588,0.914459,0.916725,0.914453,0.916719
7,LLVM,regression,0.922256,0.920339,0.924332,0.920185,0.924185
4,SQLite,classification,0.739396,0.745336,0.727083,0.751702,0.733742
11,SQLite,regression,0.745185,0.751093,0.733222,0.757141,0.739554

In [40]:
dfResults[dfResults["type"]=="regression"][["Accuracy"]].mean() - dfResults[((dfResults["type"]=="classification") & (dfResults["name"]!="JavaGC"))][["Accuracy"]].mean()

Accuracy    0.006088
dtype: float64

In [39]:
dfResults[((dfResults["type"]=="classification") & (dfResults["name"]!="JavaGC"))][["Accuracy"]].mean()

Accuracy    0.912283
dtype: float64